owner: developermelodi # GitHub username
repo: mm_monitors # GitHub repository name
sites: # List of endpoints to track
  - name: Googlee
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - developermelodi
status-website: # Status website (optional)
  cname: developermelodi.github.io # Custom domain CNAME
  #name: Upptime # Status website title

